/**
 * Client-side PDF export — no PDF library needed. Opens a clean, branded,
 * print-optimized document in a new tab and triggers the browser's print
 * dialog, where "Save as PDF" produces the actual file. This keeps the
 * dependency footprint at zero (matches the project's existing convention:
 * CSV export in lib/csv.js works the same way — pure browser APIs).
 */
function escapeHtml(value) {
  return String(value ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
}

/**
 * @param {Object} report
 * @param {string} report.title
 * @param {string} report.rangeLabel
 * @param {{label:string, value:string|number}[]} report.stats - headline tiles
 * @param {{heading:string, rows:{label:string, value:string|number}[], emptyText?:string}[]} report.sections
 */
export function openPrintableReport({ title, rangeLabel, stats, sections }) {
  const win = window.open("", "_blank");
  if (!win) {
    throw new Error("Your browser blocked the print window. Please allow popups for this site.");
  }

  const statsHtml = stats
    .map(
      (s) => `<div class="stat">
        <div class="stat-value">${escapeHtml(s.value)}</div>
        <div class="stat-label">${escapeHtml(s.label)}</div>
      </div>`
    )
    .join("");

  const sectionsHtml = sections
    .map((section) => {
      const rowsHtml = section.rows.length
        ? section.rows
            .map((r) => `<tr><td>${escapeHtml(r.label)}</td><td class="num">${escapeHtml(r.value)}</td></tr>`)
            .join("")
        : `<tr><td colspan="2" class="empty">${escapeHtml(section.emptyText || "No data in this range.")}</td></tr>`;
      return `<section>
        <h2>${escapeHtml(section.heading)}</h2>
        <table>${rowsHtml}</table>
      </section>`;
    })
    .join("");

  win.document.write(`<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>${escapeHtml(title)}</title>
<style>
  @page { margin: 24mm 18mm; }
  * { box-sizing: border-box; }
  body {
    font-family: -apple-system, "Segoe UI", Inter, Arial, sans-serif;
    color: #0f1c2e;
    margin: 0;
    padding: 32px;
  }
  header { border-bottom: 2px solid #c9a84c; padding-bottom: 16px; margin-bottom: 24px; }
  h1 { font-size: 22px; margin: 0 0 4px; }
  .range { color: #64748b; font-size: 13px; }
  .stats { display: flex; gap: 12px; margin-bottom: 28px; flex-wrap: wrap; }
  .stat { flex: 1 1 120px; border: 1px solid #e2e8f0; border-radius: 8px; padding: 12px 14px; }
  .stat-value { font-size: 22px; font-weight: 700; color: #0f1c2e; }
  .stat-label { font-size: 11px; color: #64748b; margin-top: 2px; }
  section { margin-bottom: 22px; break-inside: avoid; }
  h2 { font-size: 13px; text-transform: uppercase; letter-spacing: 0.03em; color: #0f1c2e; margin: 0 0 8px; }
  table { width: 100%; border-collapse: collapse; font-size: 13px; }
  td { padding: 6px 4px; border-bottom: 1px solid #f1f5f9; }
  td.num { text-align: right; font-weight: 600; }
  td.empty { color: #94a3b8; text-align: center; padding: 14px 4px; }
  footer { margin-top: 32px; font-size: 10px; color: #94a3b8; text-align: center; }
  @media print { body { padding: 0; } }
</style>
</head>
<body>
  <header>
    <h1>${escapeHtml(title)}</h1>
    <div class="range">${escapeHtml(rangeLabel)}</div>
  </header>
  <div class="stats">${statsHtml}</div>
  ${sectionsHtml}
  <footer>Generated by Finuxia — communication &amp; pipeline data only, no investment or financial advice.</footer>
</body>
</html>`);
  win.document.close();

  // Give the new tab a moment to lay out before opening the print dialog.
  // Guarded so onload + the fallback timer can never both fire it.
  let printed = false;
  const triggerPrint = () => {
    if (printed || win.closed) return;
    printed = true;
    win.focus();
    win.print();
  };
  win.onload = triggerPrint;
  // Fallback for browsers that don't fire onload reliably for document.write.
  setTimeout(triggerPrint, 300);
}
